theme: jekyll-theme-minimal
title: David
description: Network Administrator by Cisco.
logo: /assets/img/Logo.jpg
show_downloads: false
google_analytics: https://www.googletagmanager.com/gtag/js?id=G-85SZW75T9Q
